### ISSUE TITLE
Crashes the game when it can't get internet connection

### ISSUE THREAD

**Issue by aminecraftplayerx** [SpaceGameDev568/ModUpdateNotifier#1]
### Operating System

Windows 10/11

### Environment

Single Player

### Game Version

Stable

### SML Version

Latest

### Mod Version

Latest

### Describe the bug

If I try to run satisfactory with my firewall on, the game crashes. If I turn the firewall off, it no longer crashes. In addition, the trace points directly to this mod as the cause of the crash. Remove All Annoyances is the only mod I have installed during this testing.

### Expected Behavior

It shouldn't crash the game

**Comment by SpaceGameDev568** [comment]
Hi, thanks for reaching out about this issue! I'll need more information to help you though, so before launching the game again, open the Mod Manager and use the "[Generate debug info](https://docs.ficsit.app/satisfactory-modding/latest/faq.html#_where_can_i_find_the_games_log_files)" option, then send the zip file here.
![image](https://github.com/user-attachments/assets/69850fb0-15b1-4a96-8704-0edf05992adb)

**Comment by SpaceGameDev568** [comment]
Hey, is this still an issue for you? If so, I can't progress in fixing it until you provide the debug information.

**Comment by SpaceGameDev568** [comment]
I'm closing this issue as stale since it's been two weeks since this was opened and you haven't responded.
